export const MAIN_NAVIGATION_ACTION = "MAIN_NAVIGATION_ACTION";
export const RECIVE_URINE_RESULTS = "RECIVE_URINE_RESULTS";
export const SHOW_RESULTS_MODAL = "SHOW_RESULTS_MODAL";
export const RESULTS_DETAILS_NAME = "RESULTS_DETAILS_NAME";
export const RESULTS_DETAILS_DATA = "RESULTS_DETAILS_DATA";
export const SHOW_ADD_MODAL = "SHOW_ADD_MODAL";
export const SET_MODAL = "SET_MODAL";
